name: burkyburk
description: generally specific 

markdown: kramdown
highlighter: pygments
logo: false
paginate: 5
paginate_path: "/blog/page:num/"
baseurl: 
domain_name: 'http://www.burkyburk.github.io'

# Details for the RSS feed generator
url:            'http://www.burkyburk/blog'
author:         'Jacob Burkhart'
